name: Data Collection Workflow

permissions:
  contents: write

on:
  schedule:
    # Monday to Thursday at 5:00 PM ET (21:00 UTC)
    - cron: '0 21 * * 1-4'  # '0 21 * * 1-4'
    # Friday at 5:00 PM ET (21:00 UTC)
    - cron: '0 21 * * 5'
    # Monday to Friday at 5:30 PM Singapore time (09:30 UTC)
    - cron: '30 9 * * 1-5'
  workflow_dispatch:  # Allow manual triggering

jobs:
  collect_overview:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || (github.event.schedule == '0 21 * * 1-4')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas pytz finvizfinance requests
      
      - name: Run finviz collect_overview
        run: |
          # Copy the patch file first
          cp collector/finviz_patch.py .
          python collector/finviz.py --data-type overview
        timeout-minutes: 15
      
      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add data/
          git commit -m "Data collection: overview ($(date))" || echo "No changes to commit"
          git pull --rebase origin main
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main

  run_finviz_main:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || (github.event.schedule == '0 21 * * 5')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas pytz finvizfinance requests
      
      - name: Run finviz main
        run: |
          # Copy the patch file first
          cp collector/finviz_patch.py .
          python collector/finviz.py --data-type all
        timeout-minutes: 50
      
      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add data/
          git commit -m "Data collection: full finviz ($(date))" || echo "No changes to commit"
          git pull --rebase origin main
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main

  run_sg_hk:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || (github.event.schedule == '30 9 * * 1-5')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Add necessary libraries for sg_spot.py and hk.py
          pip install pandas pytz requests openpyxl
      
      - name: Run Singapore and Hong Kong scripts
        run: |
          python collector/sg_spot.py
          python collector/hk.py
      
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/
          git commit -m "Data collection: SG and HK ($(date))" || echo "No changes to commit"
          git pull --rebase origin main
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main

